month 7/step 1
AlexeyKrutyakov/react-stellar-burger pull request #1
Opened 2023-08-07 18:35 UTC by AlexeyKrutyakov

2023-08-07 20:53 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Проект соответствует макету
- Хорошая декомпозиция компонентов
- Хороший `codestyle` - логичный и понятный код

Необходимо исправить:
- Добавьте isRequired для обязателных пропсов в `propTypes`

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-08-07 20:53 UTC, andryxxa93 commented on src/components/ingridients-gallery/ingridients-gallery.jsx
> +  type: PropTypes.string,
**Надо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте

2023-08-07 20:53 UTC, andryxxa93 commented on src/components/ingridients-card/ingridients-card.jsx
> +function IngridientsCard(props) {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2023-08-07 20:53 UTC, andryxxa93 commented on src/components/burger-ingridients/burger-ingridients.jsx
> +function BurgerIngridients() {
**Можно лучше**
при клике на соответвующий таб должен происходить скролл к нужному разделу в списке ингредиентов

Для этого можно задать каждому заголовку соотвующий id (или использовать refы) и вызывать scrollIntoView
Например:

```
  const setTab = (tab) => {
    setCurrent(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };

```

где заголовкам разделов заданы соответсвующие атрибуты id
https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2023-08-08 20:51 UTC, AlexeyKrutyakov commented on src/components/ingridients-gallery/ingridients-gallery.jsx
> +  type: PropTypes.string,
исправлено

2023-08-08 20:53 UTC, AlexeyKrutyakov commented on src/components/ingridients-card/ingridients-card.jsx
> +function IngridientsCard(props) {
исправлено

2023-08-08 21:54 UTC, AlexeyKrutyakov commented on src/components/burger-ingridients/burger-ingridients.jsx
> +function BurgerIngridients() {
исправил

2023-08-08 21:57 UTC, AlexeyKrutyakov commented
Здравствуйте!
Спасибо за ревью!
Вроде всё поправил

2023-08-09 12:03 UTC, andryxxa93 commented
Промежуточная работа принята! Вы можете приступать к финальному этапу сдачи работы. 
Удачи!

2023-08-14 22:14 UTC, merged