month-9/step-1
AlexeyKrutyakov/react-stellar-burger pull request #5
Opened 2023-10-11 20:08 UTC by AlexeyKrutyakov

2023-10-11 20:51 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Сильные стороны работы:
- Защита роутов реализована в одном компоненте
- Правильно организован роутинг модальных окон
- Настроены все редиректы

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- На тег form нужно навешивать обработчик onSubmit, а не обработчик onClick на кнопку сабмита.
- Страница конструктора должна быть доступна для неавторизованных юзеров
- Роут `reset-password` должен быть доступен только через роут` forgot-password`
-  Обновление токена должно работать так же и на запросе изменяющем данные юзера

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-10-11 20:51 UTC, andryxxa93 commented on src/components/app/app.jsx
> +  const ingredients = useSelector(state => state.ingredients);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-10-11 20:51 UTC, andryxxa93 commented on src/components/app/app.jsx
> +          <Route path='/profile' element={<OnlyAuth component={<ProfilePage />} />}>
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-10-11 20:51 UTC, andryxxa93 commented on src/pages/forgot-password/forgot-password-page.jsx
> +  useEffect(() => {
**Можно лучше**
Точно ли нужно, чтобы данный хук срабатывал каждый рендер? 
Вот тут есть пару вариантов как это можно сделать без `useEffect` https://stackoverflow.com/questions/46160461/how-do-you-set-the-document-title-in-react

2023-10-11 20:51 UTC, andryxxa93 commented on src/pages/ingredient/ingredient-page.jsx
> +        </article>
**Можно лучше**
нарушено форматирование кода - проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Практически все современные редакторы умеют автоматически форматировать код. В vscode для этого **достаточно нажать F1 и в выпадающем списке выбрать пункт Format Document**.
 Постарайтесь использовать автоматическое форматирование, это сильно экономит время, а Ваш код будет всегда красив. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

2023-10-11 20:51 UTC, andryxxa93 commented on src/pages/profile-settings/profile-settings-page.jsx
> +  function inputNameHandler(event) {
**Можно лучше**

Можно сделать универсальный **кастомный** хук для контроля любого количества инпутов в любых формах:
```js
 export function useForm(inputValues) {
   const [values, setValues] = useState(inputValues);
 
   const handleChange = (event) => {
     const {value, name} = event.target;
     setValues({...values, [name]: value});
   };
   return {values, handleChange, setValues};
 }
```
    
Этот код помещают в отдельный файл `useForm.js` в папке `hooks` и импортируют функцию туда, где нужно контролировать инпуты

 И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:
    
 ```js
   const {values, handleChange, setValues} = useForm({});
 ```

2023-10-12 19:10 UTC, AlexeyKrutyakov commented on src/components/app/app.jsx
> +  const ingredients = useSelector(state => state.ingredients);
заменил именованными функциями

2023-10-12 21:53 UTC, AlexeyKrutyakov commented on src/components/app/app.jsx
> +          <Route path='/profile' element={<OnlyAuth component={<ProfilePage />} />}>
записал роуты в константы

2023-10-12 21:55 UTC, AlexeyKrutyakov commented on src/pages/ingredient/ingredient-page.jsx
> +        </article>
всё поправил с помощью `prettier`

2023-10-12 22:19 UTC, AlexeyKrutyakov commented on src/pages/forgot-password/forgot-password-page.jsx
> +  useEffect(() => {
поправил везде на срабатывание только при монтировании
к сожалению не понял, как можно реализовать функционал без `useEffect`

2023-10-13 12:39 UTC, AlexeyKrutyakov commented on src/pages/profile-settings/profile-settings-page.jsx
> +  function inputNameHandler(event) {
супер полезное замечание! спасибо!
первый мой хук!
очень понравилось
всё поправил во всех формах

2023-10-13 17:05 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-10-14 00:05 UTC, merged